// =============================================================================
// CI/CD GENERATION
// =============================================================================

import { GeneratedFile, Gap, RepoContext } from '../types'

/**
 * Generate CI/CD configuration
 */
export async function generateCICD(
  ctx: RepoContext,
  gaps: Gap[]
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = []
  
  // Generate GitHub Actions if no CI
  const noCI = gaps.find(g => g.id === 'deploy-no-ci')
  if (noCI) {
    files.push(...generateGitHubActions(ctx))
  }
  
  // Generate Dockerfile if needed
  const noDocker = gaps.find(g => g.id === 'deploy-no-docker')
  if (noDocker) {
    files.push(...generateDockerfile(ctx))
  }
  
  return files
}

/**
 * Generate GitHub Actions workflows
 */
function generateGitHubActions(ctx: RepoContext): GeneratedFile[] {
  const packageManager = ctx.techStack.packageManager || 'npm'
  const runCmd = packageManager === 'pnpm' ? 'pnpm' : packageManager === 'yarn' ? 'yarn' : 'npm run'
  const installCmd = packageManager === 'pnpm' ? 'pnpm install' : 
                     packageManager === 'yarn' ? 'yarn install --frozen-lockfile' : 
                     'npm ci'
  
  return [{
    path: '.github/workflows/ci.yml',
    content: `# =============================================================================
# CI Pipeline
# =============================================================================
# Generated by inprod.ai

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: '${packageManager}'
      
      - name: Install dependencies
        run: ${installCmd}
      
      - name: Run ESLint
        run: ${runCmd} lint
      
      - name: Type Check
        run: ${runCmd} typecheck || npx tsc --noEmit

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: '${packageManager}'
      
      - name: Install dependencies
        run: ${installCmd}
      
      - name: Run Tests
        run: ${runCmd} test
        env:
          CI: true
      
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        if: always()
        continue-on-error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: '${packageManager}'
      
      - name: Install dependencies
        run: ${installCmd}
      
      - name: Build
        run: ${runCmd} build
        env:
          SKIP_ENV_VALIDATION: true
`,
    language: 'yaml',
    category: 'deployment',
    confidence: 95,
    description: 'GitHub Actions CI pipeline',
  }, {
    path: '.github/workflows/security.yml',
    content: `# =============================================================================
# Security Scanning
# =============================================================================
# Generated by inprod.ai

name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday

jobs:
  dependency-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Audit Dependencies
        run: npm audit --audit-level=high
        continue-on-error: true

  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect Secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`,
    language: 'yaml',
    category: 'deployment',
    confidence: 92,
    description: 'GitHub Actions security scanning',
  }]
}

/**
 * Generate Dockerfile
 */
function generateDockerfile(ctx: RepoContext): GeneratedFile[] {
  const isNextJS = ctx.techStack.frameworks.includes('next.js')
  
  if (isNextJS) {
    return [{
      path: 'Dockerfile',
      content: `# =============================================================================
# DOCKERFILE - Next.js Production Build
# =============================================================================
# Generated by inprod.ai

FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --only=production

# Rebuild source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build the application
ENV NEXT_TELEMETRY_DISABLED 1
ENV SKIP_ENV_VALIDATION true
RUN npm run build

# Production image
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]
`,
      language: 'dockerfile',
      category: 'deployment',
      confidence: 92,
      description: 'Docker configuration for Next.js',
    }, {
      path: 'docker-compose.yml',
      content: `# =============================================================================
# DOCKER COMPOSE - Local Development
# =============================================================================
# Generated by inprod.ai

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local

  # Uncomment for local database
  # db:
  #   image: postgres:15-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: myapp
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
`,
      language: 'yaml',
      category: 'deployment',
      confidence: 88,
      description: 'Docker Compose configuration',
    }, {
      path: '.dockerignore',
      content: `# =============================================================================
# DOCKERIGNORE
# =============================================================================
# Generated by inprod.ai

# Dependencies
node_modules
.pnpm-store

# Build outputs
.next
dist
build
out

# Development
.git
.gitignore
*.md
*.log

# Environment
.env*
!.env.example

# IDE
.idea
.vscode
*.swp

# Testing
coverage
.nyc_output
e2e
tests

# OS
.DS_Store
Thumbs.db
`,
      language: 'plaintext',
      category: 'deployment',
      confidence: 95,
      description: 'Docker ignore file',
    }]
  }
  
  // Generic Node.js Dockerfile
  return [{
    path: 'Dockerfile',
    content: `# =============================================================================
# DOCKERFILE - Node.js Application
# =============================================================================
# Generated by inprod.ai

FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy source
COPY . .

# Build if needed
RUN npm run build --if-present

EXPOSE 3000

CMD ["node", "dist/index.js"]
`,
    language: 'dockerfile',
    category: 'deployment',
    confidence: 85,
    description: 'Docker configuration for Node.js',
  }]
}

